name: ©EREMONY CI

on:
  push:
  pull_request:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      id: build
      with:
        node-version-file: .nvmrc
    - run: |
        npm install
        npm run build
        zip -r build.zip build
    - name: Get branch name
        id: branch-names
        uses: tj-actions/branch-names@v8
.
    - uses: ncipollo/release-action@v1
      id: release
      with:
        artifacts: "build.zip"
        name: "${{ steps.branch-names.outputs.current_branch }}"
        tag: "${{ steps.branch-names.outputs.current_branch }}"

