name: ©EREMONY CI

on:
  push:
  pull_request:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: NPM Install and Build
        id: build
        with:
          node-version-file: .nvmrc
      - run: |
          npm install --legacy-peer-deps
          UNIVERSAL_GA_ACCOUNT_ID=${{ secrets.UNIVERSAL_GA_ACCOUNT_ID }} npm run build
          zip -r build.zip build
      - name: Get branch name
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Delete release
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: "${{ steps.branch-names.outputs.current_branch }}"
          token: "${{ github.token }}"

      - uses: ncipollo/release-action@v1
        name: Release Zip
        id: release
        with:
          artifacts: "build.zip"
          name: "${{ steps.branch-names.outputs.current_branch }}"
          tag: "${{ steps.branch-names.outputs.current_branch }}"
          generateReleaseNotes: true
          makeLatest: ${{ github.ref == 'refs/heads/main' && true || false }}
